name: First interaction
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  first-interaction:
    runs-on: ubuntu-latest
    steps:
    - name: First interaction
      uses: actions/first-interaction@v1.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Thank you for opening your first issue! We’re glad to have you here. Our team will review it shortly. 
          Meanwhile, feel free to check out the [CONTRIBUTING](CONTRIBUTING.md) guide.
        pr-message: >
          Thank you for submitting your first pull request! 🎉 We value your contribution. 
          Please ensure you’ve followed the [CONTRIBUTING](CONTRIBUTING.md) guide. 
